# Generated by Django 4.1.2 on 2022-10-21 22:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.CharField(max_length=2000)),
                ('publicacion', models.DateField(default=datetime.date.today)),
                ('rating', models.IntegerField(default=5)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.autor')),
            ],
        ),
    ]
